const actionTypes = {
	USER_LOGIN_START: 'USER_LOGIN_START',
	USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
	USER_LOGIN_DONE: 'USER_LOGIN_DONE',

	UPDATE_LOGIN_FORM_CONTEXT: 'UPDATE_LOGIN_FORM_CONTEXT'
};

export default actionTypes;
